{{- if .Values.quota.enabled }}
---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.name }}
    backstage.io/kubernetes-id: {{ .Values.name }}
spec: {{ toYaml .Values.quota.resources | nindent 2 }}
{{- end }}