{{- if .Values.istioGateway.private.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-priv-{{ .Values.global.application.cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.istioGateway.namespace }}
    server: {{ .Values.global.application.cluster.server }}
  project: {{ .Values.global.application.project }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.14.1
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
      {{- with .Values.istioGateway.private.values }}
      values: |-
      {{- toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway-priv
  namespace: istio-ingress
spec:
  selector:
    app: {{ default "istio-ingress-priv" .Values.istioGateway.private.values.name }}
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
  {{- with .Values.istioGateway.private.gateway.servers }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

{{- end }}
