{{- if .Values.promtail.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-{{ .Values.global.application.cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.promtail.namespace }}
    server: {{ .Values.global.application.cluster.server }}
  project: {{ .Values.global.application.project }}
  source:
    chart: promtail
    helm:
      valueFiles:
      - values.yaml
      {{- with .Values.promtail.values }}
      values: |-
      {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.0.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
